### ISSUE TITLE
샘플 프로젝트 전면 개편

### ISSUE THREAD

**Issue by hyunjun19** [axisj/axu4j#31]
샘플 프로젝트 전면 개편

현재 model1과 egovframework 두 가지로 분리되어 있는 샘플을 하나로 합치고 좀 더 체계적인 샘플 프로젝트로 만들것...

table, pjax 샘플 추가 필요

**Comment by hyunjun19** [comment]
일단... 폐기

**Comment by thomasJang** [comment]
ㅎㅎㅎㅎ
