### ISSUE TITLE
[axu4j-egovframe 예제] 사용법 관련 질문 건

### ISSUE THREAD

**Issue by dsjeong** [axisj/axu4j#33]
안녕하세요.
WEB 개발을 막 시작하고 있는 개발자 입니다.

요즘 axisj ,axu 관련하여 관심이 있어 많이 찾아보고 있습니다.
github에 올려주신 axu4j-egovframe 예제 관련 질문을 몇 가지 드리고자 합니다.

ㅁ예제실행방법 질문
     [문제상황]
      - 예제 분석을 위해 디버깅 모드(중단점 사용, 변수 내부값 확인 등) 실행을 하고자 하여
        Run As > Run Configurations 화면에서 "Goals: tomcat7:run -X" or "Debug Outout 체크" 설정 후, 
        Run 하였으나, 중단점에 걸리지 않음.
      - 또한, 일반적인 Project 구동방식으로 axu4j-egovframe에 tomcat 지정 후
        "Run As > Run on Server"혹"Debug As > Debug on Server"로 실행 시
         HTTP Status 404 - /actionLogin.do 에러 발생
     [질문]
      - axu4j-egovframe(Maven Project)를 디버깅하는 방법에 대해서 조언을 얻고자 합니다.
        가능하다면,  "Run As > Run on Server"혹"Debug As > Debug on Server" 실행 시 왜
        Error가 나는지에 대해서도 답변을 부탁드려요.
 
ㅁ다른 개발자와 공유방법 질문
     [문제상황]
      - axu4j-egovframe 예제에 추가/수정(java, jps 파일 수정 및 jar 신규 추가 등)하여 
        재 개발한 결과물을 다른 개발자가 자신의 PC Eclipse에서 동일하게 File > Import / Existing
         Maven Projects 사용하고자 함
     [질문]
      - 재 개발한 결과물을 다른 개발자에게 공유코자 할때 어떠한 추가 작업들이 필요한지 여쭙습니다.
       (예를 들어,  Run As - Maven build.. / Maven - Add Dependency.. 등 어떠한 작업들이 필요한지) 

질문을 드리다보니, axu4j 보다는 Web 관련 쪽 내용이라서 죄송.......(_ _)
답변 부탁드립니다^^
수고하세요.

감사합니다.

**Comment by hyunjun19** [comment]
일단 해당 프로젝트는 `Maven` 이라는 빌드 도구로 구성되어 있습니다.
메이븐에 대해 좀 더 공부해 보시면 많은 도움이 될껍니다.

1. 예제실행방법
    - `Run As`가 아니라 `Debug As`로 실행하셔야 합니다. 이클립스로 실행하신거 같은데요. 기본적으로 이클립스에서 `Debug As`로 돌리셔야 디버깅 모드를 사용하실 수 있습니다.
    - `Run on Server`는 이클립스의 톰캣 플러그인으로 돌리는 환경을 말하시는거 같네요. 기본적으로 이클립스의 `Dynamic Web Project`는 해당 플러그인으로 잘 돌아가겠지만 메이븐은 폴더 구조가 다르기 때문에 이클립스의 플러그인으로 돌리기가 어렵습니다. 해당 프로젝트는 메이븐 톰캣 플러그인을 사용하므로 `mvn tomcat7:run`을 실행하시면 이클립스에 별도의 톰캣 설정 없이 톰캣을 실행하실수 있습니다.
    - https://github.com/axisj/axu4j/wiki/sample-run-eclipse 여기 설명대로 따라하세요.
2. 다른 개발자와 공유방법
    - 메이븐의 폴더 구조 및 `Dependency`를 메이븐에서 권장하는 방법대로 설정하셨다면 `pom.xml`과 `src` 폴더만 VCS(버전관리시스템. SVN, git 등등)에 올리시면 됩니다.(이 예제 프로젝트는 `egovfrm.sqlite` 이 파일도 필요합니다. 이 파일이 데이터 베이스에요.)
    - 다른 개발자들은 이클립스에서 Maven Project로 임포트만 하면 모든 개발환경이 준비 됩니다.(이건 메이븐의 장점입니다.)

[README.md](https://github.com/axisj/axu4j/blob/master/axu4j-egovframe/README.md)와 [위키](https://github.com/axisj/axu4j/wiki)를 잘 읽어 보시면 도움이 될껍니다. =)

**Comment by dsjeong** [comment]
늦었지만 답변 감사드립니다.
도움이 많이 됩니다.
