### ISSUE TITLE
axu4j버그 인거 같은데 문의 드립니다.

### ISSUE THREAD

**Issue by hadesyi** [axisj/axu4j#35]
aux4j의 템플릿 엔진기능이 좋아서 사용을 하고 있습니다.
메뉴정보를 세션에 담아서 호출을 하는데 브라우저상의 주소는 정확하게 나오는데
실제 페이지는 다른 페이지가 호출하는 경우가 가끔 발생을 합니다.
<ax:write divname="scripts" /> 
여기 write tag의 문제 인지 모르겠네요
환경은 tomcat 7, jdk7, spring4.0.9 axu4j 1.2.0 입니다.
콘솔상에 에러는 나지 않습니다. 그래서 원인을 찾기가 힘드네요.

**Comment by hyunjun19** [comment]
아... 제가 이슈를 제대로 놓치고 있었네요... ㅠㅠ
일단 잘 사용하고 계신다니 정말 기쁩니다.

혹시 jsp 소스와 실제 브라우저에 렌더링된 HTML을 첨부해 주실 수 있으신가요?(필요한 부분만 올려주셔도 됩니다.)

**Comment by hadesyi** [comment]
목마른 사슴이 우물을 찾듯이 자가 해결 했습니다. 소스는 pull requests 했습니다.
layoutTag 버그 수정
-동시사용자가 많을 경우 1000번중에 1~5% 경우로 엉뚱한 페이지 호출
1.HashMap->Hashtable 변경
2.divMap=null 반환 처리 추가

**Comment by hyunjun19** [comment]
해당 버그 수정사항을 반영한 1.2.1 버전을 릴리즈 했습니다.
메이븐 저장소에도 올렸으니 내일쯤이면 메이븐에서도 1.2.1 버전이 보일껍니다.

**Comment by thomasJang** [comment]
1.2.1 릴리즈에는 부모태그가 없으면 에러 뱉는건 빼고? 한건가용?

col 만 쓰면 에러 있었는데

**Comment by hyunjun19** [comment]
@thomasJang 저는 부모없는 자식이 있으면 안된다고 생각합니다...만 필요하면 티켓을 날려주세요. ㅎㅎ
