### ISSUE TITLE
setList에 오류가 있는 것 같습니다.

### ISSUE THREAD

**Issue by forkit10** [axisj/axu4j#38]
AXISJ 너무 좋아요. ^^ 

다른 언어는 잘 다루지만 javascript는  모르는 초급자이니 질문이 너무 쌩뚱맞더라도 이해 바랍니다.
Chrome에서 개발자 도구에서 서버로 던지는 내용에서 포착한것입니다.

axisj로 AXSearch를 이용한 경우 아래 코드가 잘 작동하는데
axu4j를 이용할 경우 아래 코드가 안넘어 갑니다.

ajaxPars:{pars} <-- 이렇게만 했을 경우 AXSearch 내 각 객체의 이름과 변수로 전달이 잘 됨.
ajaxPars:{"param":pars} <-- 이렇게 했을 경우 아예 전달이 안됨.

`submit: function(){
                var pars = this.target.getParam();
                trace(pars);
				
				fnObj.grid.get().setList({
                    ajaxUrl:"http://localhost:8080/****/codeList.json", ajaxPars:{"param":pars}, onLoad:function(){
                        //trace(this);
                    }
                });
            }`

**Comment by thomasJang** [comment]
`ajaxPars: pars` 이렇게 해보세요

**Comment by forkit10** [comment]
많이 바쁘신가보네요. ㅡㅡ;;;

답변 감사합니다.
답변 주신 방법으로 할 경우 search 조건에 해당 하는 모든 파라미터가 넘어가긴 합니다.
(제 질문에도 그렇게는 정상적으로 된다고 하고 있구요.)

제가 원한 내용은 그게 아니였습니다.
